### PR TITLE
Fix for vagrant error: "==> default: stdin: is not a tty"

### PR DESCRIPTION
**Pull request by dm-cracked-sean-knight**
Comments out the "mesg n" line in /root/.profile

http://manpages.ubuntu.com/manpages/trusty/man1/mesg.1.html

Fixes https://github.com/puphpet/puphpet/issues/213

Fix similar to https://github.com/mitchellh/vagrant/issues/1673

### CODE REVIEW

**Comment by vincenzo** [comment]
Removing `mesg n` is not necessary. This should do it: 

`sed -i 's/^mesg n$/tty -s \&\& mesg n/g' /root/.profile`

It replaces `mesg n` with `tty -s && mesg n`. 

Is @jtreminio interested in this? 

The same thing, btw, should be done for debian, @dm-cracked-sean-knight.

**Comment by vincenzo** [comment]
It'd be good to get some movement on this one, @jtreminio. 
It really annoys me to see that `==> default: stdin: is not a tty` on Debian-based boxes... :)

**Comment by vincenzo** [comment]
@dm-cracked-sean-knight Did you see [my suggestion](https://github.com/puphpet/packer-templates/pull/4#issuecomment-144950297)?

**Comment by jtreminio** [comment]
Hey all, I will actually be abandoning this repo and cloning from a different source. The newest box versions are built against customized https://github.com/boxcutter configs.

I will be pushing those out shortly.

**Comment by dm-cracked-sean-knight** [comment]
@vincenzo Great suggestion, I just haven't had time to implement it.  Looks like the botcutter repo is the way to go now.

**Comment by vincenzo** [comment]
@dm-cracked-sean-knight Indeed. Thanks anyway.

**Comment by vincenzo** [comment]
@jtreminio Thanks for letting us know - how will I know when that's pushed?

**Pull request closed without merging**
